### ISSUE TITLE
TypeError: Object of type datetime is not JSON serializable

### ISSUE THREAD

**Issue by LBarry97** [mpasternak/django-password-policies#4]
I get this error when I use:
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

This package not support it?

**Comment by LBarry97** [comment]
I have already found the solution. You have to add this in the settings.py:
SESSION_SERIALIZER = 'django.contrib.sessions.serializers.PickleSerializer'

**Comment by mpasternak** [comment]
I don't exactly see how this package could be the reason for your error. Could you please paste the whole traceback eventually?

**Comment by LBarry97** [comment]
`obj

{'_auth_user_backend': 'django.contrib.auth.backends.ModelBackend',
 '_auth_user_hash': '48141e42386a535824667695bee133cc59ac2e7b',
 '_auth_user_id': '10',
 '_password_policies_change_required': False,
 '_password_policies_last_changed': datetime.datetime(2020, 8, 10, 13, 42, 22, tzinfo=<UTC>),
 '_password_policies_last_checked': datetime.datetime(2020, 8, 12, 9, 10, 7, 773736, tzinfo=<UTC>)}

self

<django.core.signing.JSONSerializer object at 0x7fb35e8b12d0>

`

> Traceback (most recent call last):
  File "/home/lbarry/.virtualenvs/a3sec-dA2I_ELU/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/lbarry/.virtualenvs/a3sec-dA2I_ELU/lib/python3.7/site-packages/django/utils/deprecation.py", line 96, in __call__
    response = self.process_response(request, response)
  File "/home/lbarry/.virtualenvs/a3sec-dA2I_ELU/lib/python3.7/site-packages/django/contrib/sessions/middleware.py", line 58, in process_response
    request.session.save()
  File "/home/lbarry/.virtualenvs/a3sec-dA2I_ELU/lib/python3.7/site-packages/django/contrib/sessions/backends/db.py", line 83, in save
    obj = self.create_model_instance(data)
  File "/home/lbarry/.virtualenvs/a3sec-dA2I_ELU/lib/python3.7/site-packages/django/contrib/sessions/backends/db.py", line 70, in create_model_instance
    session_data=self.encode(data),
  File "/home/lbarry/.virtualenvs/a3sec-dA2I_ELU/lib/python3.7/site-packages/django/contrib/sessions/backends/base.py", line 95, in encode
    serialized = self.serializer().dumps(session_dict)
  File "/home/lbarry/.virtualenvs/a3sec-dA2I_ELU/lib/python3.7/site-packages/django/core/signing.py", line 87, in dumps
    return json.dumps(obj, separators=(',', ':')).encode('latin-1')
  File "/usr/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable

**Comment by mpasternak** [comment]
Pickle has its security concerns, mind that. 

Would you like to document this somewhere in the docs? If you do, I'm willing to merge your work. Feel free to submit PR.

**Comment by LBarry97** [comment]
Okey!

**Comment by mikemanger** [comment]
Any word on removing pickle serializer as a requirement for this project? [It is referenced in the docs](https://github.com/iplweb/django-password-policies-iplweb/blob/develop/docs/topics/setup.rst#serializer). Makes it hard to recommend using this project.

**Comment by mpasternak** [comment]
Patches accepted, can you submit a PR?
