### ISSUE TITLE
Setting a large PASSWORD_DURATION_SECONDS causes an error

### ISSUE THREAD

**Issue by mikemanger** [mpasternak/django-password-policies#42]
Setting `PASSWORD_DURATION_SECONDS` to a large value gives an overflow error.
```python
# settings.py
# 23992800719976 seconds
PASSWORD_DURATION_SECONDS = 24 * 9999**3
```

```
Traceback (most recent call last):
  File "[DIR]/site-packages/password_policies/middleware.py", line 186, in process_request
    self.check = PasswordCheck(request.user)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[DIR]/site-packages/password_policies/utils.py", line 16, in __init__
    self.expiry_datetime = self.get_expiry_datetime()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[DIR]/site-packages/password_policies/utils.py", line 49, in get_expiry_datetime
    return timezone.now() - timedelta(seconds=seconds)
           ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
OverflowError: date value out of range
```

Tested with python 3.12.

**Comment by mikemanger** [comment]
I think worth catching and setting the value to `timedelta.max`.
